name: vulnerability scan workflow

on: [push, workflow_dispatch]

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: macos-latest
        steps: 
          - name: Checkout (official GitHub action)
            uses: actions/checkout@v3
            
          - name: Setup JDK 11 (official GitHub action)
            uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: 'adopt'
                        
          - name: Download the Meterian Thin CLient
            run: wget -q https://www.meterian.io/downloads/meterian-cli.jar
            
          - name: Scan project with the Meterian Thin CLient
            run: java -jar meterian-cli.jar
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
